spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
  pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) [corrId=%X{correlationId:-N/A}] [%clr(${spring.application.name}){cyan}] %clr([%thread]){yellow} %clr(%logger{36}){blue} - %msg%n"

server:  
  port: 8081
